### ISSUE TITLE
The size of tensor a (1419) must match the size of tensor b (174592) at non-singleton dimension

### ISSUE THREAD

**Issue by qingchenwuhou** [kemaloksuz/aLRPLoss#8]
Greak work!
I meet one question when I train my custom dataset:

2021-03-19 19:15:49,216 - mmdet - INFO - load model from: torchvision://resnet101
2021-03-19 19:15:49,743 - mmdet - WARNING - The model and loaded state dict do not match exactly

unexpected key in source state_dict: fc.weight, fc.bias

loading annotations into memory...
Done (t=0.75s)
creating index...
index created!
loading annotations into memory...
Done (t=0.06s)
creating index...
index created!
2021-03-19 19:15:56,242 - mmdet - INFO - Start running, host: jiangbowen@ubuntu-93, work_dir: /home/jiangbowen/lns_154data1/train_fault/code_mmcls/aLRPLoss-master/model
2021-03-19 19:15:56,243 - mmdet - INFO - workflow: [('train', 1)], max: 100 epochs
tensor([0.5118, 0.5142, 0.5315, 0.5102, 0.5339, 0.5128, 0.5315, 0.5331, 0.5205,
0.5263, 0.5197, 0.5253, 0.5213, 0.5217, 0.5264, 0.5205, 0.5247, 0.5237,
0.5099, 0.5219, 0.5117, 0.5228, 0.5140, 0.5106, 0.5100, 0.5090, 0.5192,
0.5122, 0.5214, 0.5126, 0.5221, 0.5224, 0.5242, 0.5280, 0.5229, 0.5285,
0.5241, 0.5258, 0.5271, 0.0000, 0.5029, 0.5004, 0.5045, 0.5005, 0.5024,
0.5007, 0.5011, 0.5227, 0.5224, 0.5222, 0.5205, 0.5220, 0.5307, 0.5207,
0.5222, 0.5290, 0.5224, 0.5291, 0.5236, 0.5288, 0.5169, 0.5161, 0.5171,
0.5160, 0.5188, 0.5173, 0.5187, 0.5175, 0.5194, 0.5247, 0.5250, 0.5248,
0.5242, 0.5158, 0.5130, 0.5231, 0.5225, 0.5269, 0.5199, 0.5274, 0.5158,
0.5189, 0.5181, 0.5193, 0.5328, 0.5193, 0.5300, 0.5169, 0.5203, 0.5094,
0.5198, 0.5210, 0.5028, 0.5203, 0.5214, 0.5190, 0.5165, 0.5172, 0.5187,
0.5209, 0.5239, 0.5200, 0.5245, 0.5204, 0.5244, 0.5246, 0.5246, 0.5237,
0.5242, 0.5252, 0.5118, 0.5138, 0.5185, 0.5220, 0.5182, 0.5116, 0.5122,
0.5194, 0.5233, 0.5210, 0.5245, 0.5240, 0.5244, 0.5245, 0.5112, 0.5244,
0.5232, 0.5236, 0.5241, 0.5108, 0.5082, 0.5119, 0.5186, 0.5188, 0.5182,
0.5177, 0.5206, 0.5218, 0.5205, 0.5197, 0.5248, 0.5231, 0.5213, 0.5209,
0.5232, 0.5201, 0.5228, 0.5200, 0.5160, 0.5123, 0.5253, 0.5151, 0.5128,
0.5218, 0.5186, 0.5194, 0.5186, 0.5186, 0.5188, 0.5200, 0.5233, 0.5181,
0.5228, 0.5208, 0.5188, 0.5174, 0.5161, 0.5240, 0.5201, 0.5213, 0.5226,
0.5224, 0.5167, 0.5160, 0.5223, 0.5244, 0.5140, 0.5136, 0.5246, 0.5262,
0.5135, 0.5242, 0.5199, 0.5248, 0.5212, 0.5199, 0.5187, 0.5233, 0.5204,
0.5226, 0.5216, 0.5202, 0.5207, 0.5191, 0.5207, 0.5234, 0.5195, 0.5232,
0.5226, 0.5186, 0.5162, 0.5168, 0.5232, 0.5138, 0.5178, 0.5227, 0.5178,
0.5215, 0.5221], device='cuda:2')
torch.Size([209])
tensor([0., 0., 0., ..., 0., 0., 0.], device='cuda:2', grad_fn=)
torch.Size([21824])
tensor(294862.1250, device='cuda:2')
torch.Size([])
tensor(294971.2188, device='cuda:0')
torch.Size([])
Traceback (most recent call last):
File "./tools/train.py", line 153, in
main()
File "./tools/train.py", line 149, in main
meta=meta)
File "/home/jiangbowen/anaconda3/envs/pytorch_1_5/lib/python3.7/site-packages/mmdet-2.1.0+unknown-py3.7-linux-x86_64.egg/mmdet/apis/train.py", line 128, in train_detector
runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
File "/home/jiangbowen/anaconda3/envs/pytorch_1_5/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 122, in run
epoch_runner(data_loaders[i], **kwargs)
File "/home/jiangbowen/anaconda3/envs/pytorch_1_5/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 32, in train
**kwargs)
File "/home/jiangbowen/anaconda3/envs/pytorch_1_5/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 31, in train_step
return self.module.train_step(*inputs[0], **kwargs[0])
File "/home/jiangbowen/anaconda3/envs/pytorch_1_5/lib/python3.7/site-packages/mmdet-2.1.0+unknown-py3.7-linux-x86_64.egg/mmdet/models/detectors/base.py", line 237, in train_step
losses = self(**data)
File "/home/jiangbowen/anaconda3/envs/pytorch_1_5/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in call
result = self.forward(*input, **kwargs)
File "/home/jiangbowen/anaconda3/envs/pytorch_1_5/lib/python3.7/site-packages/mmdet-2.1.0+unknown-py3.7-linux-x86_64.egg/mmdet/core/fp16/decorators.py", line 51, in new_func
return old_func(*args, **kwargs)
File "/home/jiangbowen/anaconda3/envs/pytorch_1_5/lib/python3.7/site-packages/mmdet-2.1.0+unknown-py3.7-linux-x86_64.egg/mmdet/models/detectors/base.py", line 172, in forward
return self.forward_train(img, img_metas, **kwargs)
File "/home/jiangbowen/anaconda3/envs/pytorch_1_5/lib/python3.7/site-packages/mmdet-2.1.0+unknown-py3.7-linux-x86_64.egg/mmdet/models/detectors/single_stage.py", line 94, in forward_train
gt_labels, gt_bboxes_ignore)
File "/home/jiangbowen/anaconda3/envs/pytorch_1_5/lib/python3.7/site-packages/mmdet-2.1.0+unknown-py3.7-linux-x86_64.egg/mmdet/models/dense_heads/base_dense_head.py", line 54, in forward_train
losses = self.loss(*loss_inputs, gt_bboxes_ignore=gt_bboxes_ignore)
File "/home/jiangbowen/anaconda3/envs/pytorch_1_5/lib/python3.7/site-packages/mmdet-2.1.0+unknown-py3.7-linux-x86_64.egg/mmdet/core/fp16/decorators.py", line 131, in new_func
return old_func(args, **kwargs)
File "/home/jiangbowen/anaconda3/envs/pytorch_1_5/lib/python3.7/site-packages/mmdet-2.1.0+unknown-py3.7-linux-x86_64.egg/mmdet/models/dense_heads/alrp_loss_retina_head.py", line 219, in loss
losses_cls, rank, order = self.aLRP_Loss.apply(flat_preds, flat_labels, loss_bbox)
File "/home/jiangbowen/anaconda3/envs/pytorch_1_5/lib/python3.7/site-packages/mmdet-2.1.0+unknown-py3.7-linux-x86_64.egg/mmdet/models/losses/alrp_loss.py", line 60, in forward
fg_grad[ii] = -(torch.sum(fg_relationsregression_losses)+FP_num)/rank[ii]
RuntimeError: The size of tensor a (209) must match the size of tensor b (21824) at non-singleton dimension 0
(pytorch_1_5) jiangbowen@ubuntu-93:~/lns_154data1/train_fault/code_mmcls/aLRPLoss-master$

Do you have any suggestion?
Thank you!

**Comment by kemaloksuz** [comment]
Hi,

It looks like there is problem with the inputs of the loss in the following line:

https://github.com/kemaloksuz/aLRPLoss/blob/2cfaa8ec3150692cca8b085221f1bd8c8c78db8e/mmdet/models/dense_heads/alrp_loss_retina_head.py#L219

Please check the following. 

flat_preds should be a vector captures unnormalized outputs obtained before sigmoid.
flat_labels should be a vector for labels of flat_preds. If an example is positive, negative or ignored; the corresponding element is 1, 0 and -1 respectively. 
loss_bbox is a vector containing the normalized IoU/GIoU Errors of only positive examples. The orders of the losses should follow the positive examples in flat_preds and flat_labels, such that all three inputs match. 

As a validation check: number of 1s in flat_preds should match the size of loss_bbox (they are both the number of positives), so before you apply the loss, it can be better to validate this.

**Comment by qingchenwuhou** [comment]
Thank you. 
I refresh the config file according to config file in coco training set after I run training on coco dataset fluently, the problem is solved.
